name: Deploy Documentation

on:
  push:
    branches:
      - master
      - demo/docusaurus

jobs:
  deploy:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - uses: actions/setup-node@master
        with:
          node-version: 14.x

      - name: Install dependencies
        run: yarn install --frozen-lockfile
        working-directory: ./website

      - name: Build static
        run: yarn build
        working-directory: ./website

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.3
        with:
          branch: gh-pages
          folder: website/build