name: Run tests

on: [push]

jobs:
  test-build:
    runs-on: ubuntu-18.04
    timeout-minutes: 15
    env:
      ALGOLIA_KEY: ${{ secrets.ALGOLIA_KEY }}
      GA_ID: ${{ secrets.GA_ID }}
      HOTJAR_ID: ${{ secrets.HOTJAR_ID }}

    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - uses: actions/setup-node@master
        with:
          node-version: 14.x

      - name: Install dependencies
        run: yarn install --frozen-lockfile
        working-directory: ./website

      - name: Check build
        run: yarn build
        working-directory: ./website
  test-lint:
    runs-on: ubuntu-18.04
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - uses: actions/setup-node@master
        with:
          node-version: 14.x

      - name: Install dependencies
        run: yarn install --frozen-lockfile
        working-directory: ./website

      - name: Check linting
        run: yarn run test:lint
        working-directory: ./website
